name: Random Measure
author: Tony Chen
email: tchen1998@gmail.com
description: A series of notebooks on topics in statistics and machine learning.
url: "chentau.github.io"
baseurl: "/blog"
markdown: kramdown

